apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbit-mq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: default
    - protocol: TCP
      port: 15672
      targetPort: 15672
      name: management