apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbit-mq
  name: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
         app: rabbit-mq
    spec:
      containers:
      - image: rabbitmq:3.8.2-management
        name: rabbit-mq
        resources:
          limits:
            memory: "270Mi"
            cpu: "250m"
        ports:
        - containerPort: 15672
        - containerPort: 15671
        - containerPort: 5671
      restartPolicy: Always
     
